name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpng-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c(
            "MASS", "stats", "future", "future.apply",
            "testthat", "rmarkdown", "knitr"
          ), repos = "https://cran.rstudio.com")'

      - name: Build and check (skip vignettes)
        run: |
          R CMD build . --no-build-vignettes
          PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
          R CMD check "${PKG_TARBALL}" --no-manual --as-cran --no-vignettes

