name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install and check
        run: |
          Rscript -e 'install.packages(c(
            "rcmdcheck", "MASS", "stats", "future", "future.apply",
            "devtools", "testthat", "rmarkdown", "knitr"
          ), repos = "https://cran.rstudio.com");
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            build_args = c("--no-build-vignettes", "--no-manual"),
            error_on = "warning"
          )'
