on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: all
          extra-packages: any::rcmdcheck

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-build-vignettes", "--no-manual")'
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
