# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel',  http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false  # don't fail if Suggests (e.g. cmdstanr/rstan) are missing

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # Install only hard deps; also install rcmdcheck explicitly
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: "hard"         # Imports/Depends/LinkingTo ONLY
          extra-packages: any::rcmdcheck
          needs: check

      # Run R CMD check; skip vignettes and manual to avoid rmarkdown/LaTeX issues
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-build-vignettes", "--no-manual", "--compact-vignettes=gs+qpdf")'
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
