on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      # 🚀 Install dependencies manually instead of using pak
      - name: Install dependencies
        run: |
          install.packages(c(
            "MASS", "stats", "future", "future.apply",
            "rstan", "devtools", "testthat", "rmarkdown", "knitr", "rcmdcheck"
          ), repos = "https://cran.rstudio.com")

      # 🚀 Run R CMD check
      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            build_args = c("--no-build-vignettes", "--no-manual"),
            error_on = "warning"
          )

